version: '3.9'

services:

   shop-db:
      image: ${DOCKER_REGISTRY-}shop-db
      hostname: shopdb
      build:
         context: shop-db/
         dockerfile: Dockerfile
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: app_password
         SHOP_DB_USER: postgres
         SHOP_DB_PWD: app_password

   shop-api:
      image: ${DOCKER_REGISTRY-}shop-api
      hostname: shopapi
      build:
         context: shop-api/
         dockerfile: Dockerfile
      environment:
         ASPNETCORE_ENVIRONMENT: Production
         SHOP_DB_HOST: "shopdb:5432"
         SHOP_DB_USER: "postgres"
         SHOP_DB_PWD: "app_password"
         ASPNETCORE_Kestrel__Certificates__Default__Password: "A#bu#H*IB@#8bIP@#XFVGLY**O2zg8p2efy2vfp23t77:"
         ASPNETCORE_Kestrel__Certificates__Default__Path: shop-api.pfx
      ports:
      - "8081:80"
      - "5444:443"
      depends_on:
      - shop-db

   shop-webapp:
      image: ${DOCKER_REGISTRY-}shop-webapp
      build:
         context: shop-webapp/
         dockerfile: Dockerfile
      environment:
         ASPNETCORE_ENVIRONMENT: Production
         SHOP_API_HOST: "http://shopapi"
      ports:
      - "8080:80"
      - "5443:443"
      depends_on:
      - shop-db
      - shop-api
