version: '3.9'

networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge

services:
   shop-db:
      image: ${DOCKER_REGISTRY-}shop-db
      hostname: shopdb
      build:
         context: shop-db/
         dockerfile: Dockerfile
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: app_password
         SHOP_DB_USER: postgres
         SHOP_DB_PWD: app_password
      networks:
      - backend

   shop-api:
      image: ${DOCKER_REGISTRY-}shop-api
      hostname: shopapi
      build:
         context: shop-api/
         dockerfile: Dockerfile
      environment:
         ASPNETCORE_ENVIRONMENT: Production
         SHOP_DB_HOST: "shopdb:5432"
         SHOP_DB_USER: "postgres"
         SHOP_DB_PWD: "app_password"
         ASPNETCORE_Kestrel__Certificates__Default__Password: "A#bu#H*IB@#8bIP@#XFVGLY**O2zg8p2efy2vfp23t77:"
         ASPNETCORE_Kestrel__Certificates__Default__Path: shop-api.pfx
      depends_on:
      - shop-db
      networks:
      - backend

   shop-webapp:
      image: ${DOCKER_REGISTRY-}shop-webapp
      hostname: shopwebapp
      build:
         context: shop-webapp/
         dockerfile: Dockerfile
      environment:
         ASPNETCORE_ENVIRONMENT: Production
         SHOP_API_HOST: "http://shopapi"
      depends_on:
      - shop-db
      - shop-api
      networks:
      - backend

   proxy:
      image: ${DOCKER_REGISTRY-}shop-proxy
      hostname: shopproxy
      build:
         context: proxy/
         dockerfile: Dockerfile
      ports:
         - 80:80
      depends_on:
      - shop-api
      - shop-webapp
      networks:
      - frontend
      - backend